### ISSUE TITLE
[10.0] Sales > Configurable Products > Configuration Settings >> Create New = Traceback

### ISSUE THREAD

**Issue by lukebranch** [pledra/odoo-product-configurator#1]
<h1>Environment:</h1>
<ul>
<li>Ubuntu 14.04</li>
<li>Odoo 10.0c</li>
<li>PostgreSQL 9.6</li>
<li>Nginx</li>
</ul>

<h1>Steps to Reproduce:</h1>
<ul>
<li>Install product_configurator, product_configurator_wizard</li>
<li>Go to: Sales > Configurable Products > Configuration Settings >> Create New</li>
<li>The following traceback is produced:<br/>
```
Traceback (most recent call last):
  File "/odoo10/odoo10-server/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo10/odoo10-server/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/odoo10/odoo10-server/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo10/odoo10-server/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo10/odoo10-server/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo10/odoo10-server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo10/odoo10-server/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/odoo10/odoo10-server/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo10/odoo10-server/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo10/odoo10-server/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo10/odoo10-server/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo10/odoo10-server/odoo/models.py", line 5440, in onchange
    value = record[name]
  File "/odoo10/odoo10-server/odoo/models.py", line 5177, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo10/odoo10-server/odoo/fields.py", line 871, in __get__
    self.determine_draft_value(record)
  File "/odoo10/odoo10-server/odoo/fields.py", line 989, in determine_draft_value
    self._compute_value(record)
  File "/odoo10/odoo10-server/odoo/fields.py", line 927, in _compute_value
    getattr(records, self.compute)()
  File "/odoo10/custom/pledra/10.0/odoo-product-configurator/product_configurator/models/product_config.py", line 280, in _get_cfg_price
    session.value_ids.ids, custom_vals)
  File "/odoo10/custom/pledra/10.0/odoo-product-configurator/product_configurator/models/product.py", line 119, in get_cfg_price
    self.ensure_one()
  File "/odoo10/odoo10-server/odoo/models.py", line 4789, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: product.template()
```
</li>
</ul>

**Comment by lukebranch** [comment]
closed by commit:

https://github.com/pledra/odoo-product-configurator/commit/758f2c2806ccfb2832b169f1e3201e5373d96c5a

**Comment by PCatinean** [comment]
@lukebranch thank you for the report!
