### ISSUE TITLE
v10 Wizard self._get_fields_type() not implemented

### ISSUE THREAD

**Issue by brokemeisteratwork** [pledra/odoo-product-configurator#11]
Hi,
I want to create an Attribute with an Custom Value. e.g. attachment.
When I get into the step in the backend wizard. I get following error:

Odoo Server Error

Traceback (most recent call last):
  File "/vagrant/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/vagrant/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/vagrant/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/vagrant/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/vagrant/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/vagrant/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/vagrant/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/vagrant/odoo/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/vagrant/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/vagrant/odoo/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/vagrant/odoo/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/vagrant/odoo/odoo/models.py", line 1328, in load_views
    for [v_id, v_type] in views
  File "/vagrant/odoo/odoo/models.py", line 1328, in <dictcomp>
    for [v_id, v_type] in views
  File "/vagrant/addons_external/product_configurator_wizard/wizard/product_configurator.py", line 346, in fields_view_get
    toolbar=toolbar, submenu=submenu
  File "/vagrant/odoo/odoo/models.py", line 1407, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/vagrant/odoo/odoo/addons/base/ir/ir_ui_view.py", line 864, in postprocess_and_fields
    fields = Model.fields_get(None)
  File "/vagrant/addons_external/product_configurator_wizard/wizard/product_configurator.py", line 310, in fields_get
    field_types = self._get_fields_type()
AttributeError: 'product.configurator' object has no attribute '_get_fields_type'

**Comment by PCatinean** [comment]
Fixed in 601c3c412a2fc62e2dfbb1c937b91ddd1651b5f8

Thank you for reporting
