### ISSUE TITLE
Error: NameError: name 'name' is not defined

### ISSUE THREAD

**Issue by vishmehra** [pledra/odoo-product-configurator#115]
Impacted versions: Odoo 10

Steps to reproduce:
Configure product template
Order a few variants
Click on Configurable Variants
Click on a Variant

Post this behavior, the "Edit" Screen for Configurable Variants is not functioning at all. 

Current behavior:
http://10.0.0.29:8069/web/content/679-bc345ce/web.assets_backend.js:1326
Traceback:
Error: NameError: name 'name' is not defined
    at PY_ensurepy (http://10.0.0.29:8069/web/content/679-bc345ce/web.assets_backend.js:1326:65)
    at Object.py.evaluate (http://10.0.0.29:8069/web/content/679-bc345ce/web.assets_backend.js:1441:8)
    at Object.py.evaluate (http://10.0.0.29:8069/web/content/679-bc345ce/web.assets_backend.js:1450:194)
    at Object.py.eval (http://10.0.0.29:8069/web/content/679-bc345ce/web.assets_backend.js:1454:284)
    at http://10.0.0.29:8069/web/content/679-bc345ce/web.assets_backend.js:1593:110
    at iterator (http://10.0.0.29:8069/web/content/673-2c0d588/web.assets_common.js:14:183)
    at Function.<anonymous> (http://10.0.0.29:8069/web/content/673-2c0d588/web.assets_common.js:17:8)
    at _.(anonymous function) [as reduce] (http://10.0.0.29:8069/web/content/673-2c0d588/web.assets_common.js:69:526)
    at eval_contexts (http://10.0.0.29:8069/web/content/679-bc345ce/web.assets_backend.js:1591:136)
    at http://10.0.0.29:8069/web/content/679-bc345ce/web.assets_backend.js:1593:253

Expected behavior:
Variant details should be visible in the next screen without this error. 

Video/Screenshot link (optional):

![snip20170724_7](https://user-images.githubusercontent.com/14320919/28521828-0aef6dcc-703b-11e7-882b-ebd1bb067a88.png)

**Comment by andreampiovesana** [comment]
this happen also to me

Andrea Piovesana linux counter #601470 ubuntu 16.04.2www.pnlug.it


2017-07-24 13:41 GMT+02:00 vishmehra <notifications@github.com>:

**Comment by vishmehra** [comment]
Any luck getting around this error?

**Comment by vipin-sigb** [comment]
Iam also getting this.. Is this is a bug?. I think this is due to replacement of the name field.
I just tried a solution(Don't know whether it is right)
I just comment the function def fields_view_get(self, view_id=None, view_type='form',
toolbar=False, submenu=False): in product_configurator/models/product.py and then add 
```
<field name="name" position="after">
<label for="config_name" string="Product Name
 <field name="config_name"/>
</field>
<xpath expr="//field[@name='name']" position = "attributes">
<attribute name="invisible">1</attribute>
</xpath>
<xpath expr="//label[@for='name']" position="attributes">
 <attribute name="invisible">1</attribute>
 </xpath>
```
in the product_view.xml   record id  "product_form_view_custom_vals_inherit".

It just fix my error.

**Comment by vishmehra** [comment]
@vipin-sigb - Your fix seems to work. Can you please submit this as a patch to the base module?

**Comment by tw-peachy360** [comment]
@vipin-sigb It does not work for me, and i seems, that the code is missing out some chars. Just to be clear on that:
1. You commented out the entire function def fields_view_get in product_configurator/models/product.py 
2. Than you inserted:

`<field name="name" position="after">
<label for="config_name" string="Product Name
 <field name="config_name"/>
</field>
<xpath expr="//field[@name='name']" position = "attributes">
<attribute name="invisible">1</attribute>
</xpath>
<xpath expr="//label[@for='name']" position="attributes">
 <attribute name="invisible">1</attribute>
 </xpath>`

after 


> string="Product Name


shouldn't it be closed like 

> string="Product Name"/>

but still, that does not work. What am I missing? Appreciate the help!
