### ISSUE TITLE
Cannot upgrade product_configurator module after creating Restrictions or Steps

### ISSUE THREAD

**Issue by yostashiro** [pledra/odoo-product-configurator#154]
### Impacted versions:

10.0 (haven't checked other versions)

### Steps to reproduce:

- Create a Configuration Step in a configurable template.
- Try upgrading `product_configurator` module.

### Current behavior:

Upgrade cannot complete due to this error:
```
2018-10-16 09:20:54,101 12 DEBUG xxxxx odoo.service.model: IntegrityError
Traceback (most recent call last):
  File "/odoo/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo/odoo/addons/base/module/module.py", line 529, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/odoo/custom/cip-private/pr1_multi_website/module.py", line 51, in _button_immediate_function
    res=super(Module,self)._button_immediate_function(function)
  File "/odoo/odoo/odoo/addons/base/module/module.py", line 486, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo/odoo/modules/loading.py", line 409, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/odoo/odoo/odoo/addons/base/ir/ir_model.py", line 1394, in _process_end
    record.unlink()
  File "/odoo/odoo/odoo/models.py", line 3413, in unlink
    cr.execute(query, (sub_ids,))
  File "/odoo/odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "config_step_id" violates not-null constraint
DETAIL:  Failing row contains (16, 1, null, 10, 1, 5138, 2018-08-27 08:32:21.661235, 2018-08-27 08:32:21.661235).
CONTEXT:  SQL statement "UPDATE ONLY "public"."product_config_step_line" SET "config_step_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "config_step_id""
```

I do not know why the system tries to set NULL to `config_step_id` when trying to upgrade the module.

Can someone perhaps confirm this behavior? Would be great to know how to work around this issue.

The same happens when you create a Restriction record, for which the module upgrade fails due to the system trying to set NULL to `domain_id` in `product.config.line` record.

**Comment by PCatinean** [comment]
Hi@yostashiro and thanks for the report. Can you reproduce this on runbot? https://runbot.pledra.com/runbot/repo/git-gitlab-pledra-com-pledra-odoo-product-configurator-18 

Locally I could not reproduce

**Comment by yostashiro** [comment]
It was a silly mistake of mine - I created `product.config.step` records by import assigning `product_configurator` as the module part of the external id, which resulted in Odoo trying to delete these records at an upgrade attempt.  The solution was to rename the external id records, changing the module part to `__import__`.  I apologize for the confusion.
