### ISSUE TITLE
website publish doesn't work as expected

### ISSUE THREAD

**Issue by tv-openbig** [pledra/odoo-product-configurator#23]
How to recapture the problem:
1. I am logged in as admin (with proper rights for pledra configurator and website editor)
2. i have created a new configurable product in Odoo backend
3. i click on the website_publish button
4. In editor mode of website i see the start site of the configurable product.
5. If i log out as admin, i click on the "Product Configurator" menu.
6. Visible message is "No product defined".

I would expect:
On step 4 i would expect red/green button to publish/unpublish the 
configurable product.

<img width="1079" alt="bildschirmfoto 2017-02-10 um 11 01 26" src="https://cloud.githubusercontent.com/assets/8348598/22822584/534f6180-ef80-11e6-9614-593388658c66.png">

**Comment by treviser** [comment]
I do observe the same issue.

**Comment by treviser** [comment]
This is what I see in the logs when I click the "Publish"-Tile for a Configurable Template in the backend:
![selection_414](https://cloud.githubusercontent.com/assets/1814941/23970463/2927c0d2-09ca-11e7-96df-8b6ab7104828.png)

And this are the log entries:

`2017-03-15 20:50:45,889 5604 INFO interbike werkzeug: 178.194.239.84 - - [15/Mar/2017 20:50:45] "POST /web/dataset/call_button HTTP/1.1" 200 -
2017-03-15 20:50:46,026 5604 INFO interbike werkzeug: 178.194.239.84 - - [15/Mar/2017 20:50:46] "GET /shop/product/t-4002-trekking-bike-10 HTTP/1.1" 302 -
2017-03-15 20:50:46,172 5604 INFO interbike werkzeug: 178.194.239.84 - - [15/Mar/2017 20:50:46] "GET /configurator/t-4002-trekking-bike-10 HTTP/1.1" 302 -
2017-03-15 20:50:46,682 5604 WARNING interbike odoo.addons.base.ir.ir_qweb.ir_qweb: Use new syntax for '<span t-tag="span"/>
                    ' monetary widget t-options (python dict instead of deprecated JSON syntax).
`

Here I have found a solution to the problem: [https://www.odoo.com/de_DE/forum/hilfe-1/question/use-new-syntax-for-span-t-tag-span-110446](url)

**Comment by treviser** [comment]
As a workaround I did export the configuration templates using the fields "name" and "Visible on Website", then in the csv-file I did change the value of the column "website_visible" from "False" to "True" and did reimport the configuration templates.

Ooops, does not work. I get an Internal 500 error because of missing access rights.

**Comment by treviser** [comment]
I have updated to the latest github version of today, I still get the access error for the public user, see my traceback below. Any ideas?

2017-03-16 07:46:38,689 13653 WARNING interbike odoo.addons.base.ir.ir_qweb.ir_qweb: Use new syntax for '<span t-tag="span"/>
                    ' monetary widget t-options (python dict instead of deprecated JSON syntax).
2017-03-16 07:46:38,715 13653 ERROR interbike odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/website/models/ir_http.py", line 273, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 766, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 825, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 327, in checked_call
    result.flatten()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1257, in flatten
    self.response.append(self.render())
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1250, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1036, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 110, in render
    return super(View, self).render(values, engine=engine)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1056, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
    raise e
QWebException: (u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: product.product, Operation: read)', None)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_website_product_configurator_config_form_radio_1465
  File "<template>", line 5, in foreach_1462
  File "<template>", line 11, in foreach_1461
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 872, in __get__
    value = record._cache[self]
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5540, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 48, in get
    raise self.exception
AccessError: (u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: product.product, Operation: read)', None)

Error to render compiling AST
AccessError: (u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: product.product, Operation: read)', None)
Template: website_product_configurator.config_form_radio
Path: /templates/t/form/t[2]/div/div/t/div/div/img
Node: <img class="img-rounded img-responsive img-center mt8" t-att-src="website.image_url(value.product_id, 'image') if value.product_id.image else '/web/static/src/img/placeholder.png'"/>

**Comment by treviser** [comment]
I do not know, if my previous posts do help to identify the bug. 

But at least in Version 10.0 it is not possible to publish a configuration template. It is necessary to define a product first, publish it and after that you can make it configurable.

**Comment by PCatinean** [comment]
@tv-openbig @treviser thank you both for reporting, this should be fixed by: https://github.com/pledra/odoo-product-configurator/commit/40bbe5ad0d75f7e7e7db97c263236d019523ebfa
