### ISSUE TITLE
syntax error on saving attachment from backend wizard

### ISSUE THREAD

**Issue by tv-openbig** [pledra/odoo-product-configurator#8]
If i want to download an attached file from the backend configurator wizards corresponding step with custom attribute of type attachment i get an syntax error, if i click 
on the "Save as" button to download the attached file.

Uncaught SyntaxError: Unexpected token T in JSON at position 0
http://configurator-v9.pledra.com/web#id=25&view_type=form&model=sale.order&menu_id=176&action=244:1
Traceback:
SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.<anonymous> (http://configurator-v9.pledra.com/web/content/755-23145ff/web.assets_common.js:2554:379)
    at HTMLIFrameElement.dispatch (http://configurator-v9.pledra.com/web/content/755-23145ff/web.assets_common.js:740:451)
    at HTMLIFrameElement.elemData.handle (http://configurator-v9.pledra.com/web/content/755-23145ff/web.assets_common.js:713:173)

<img width="1183" alt="bildschirmfoto 2017-01-12 um 13 47 02" src="https://cloud.githubusercontent.com/assets/8348598/21890545/7b09aa6e-d8ce-11e6-9932-8b0df69ee53a.png">

**Comment by PCatinean** [comment]
The attachment save bug in the wizard should be fixed by 56e83912a270de2474199917a1aed62ea72d9753

Downloading the attachment from the configuration wizard is still something I need to look into.

Thanks for reporting, I will keep you posted
