### ISSUE TITLE
V10 CE Module uninstal -> Odoo Server Error

### ISSUE THREAD

**Issue by sharkutz** [pledra/odoo-product-configurator#93]
Impacted versions:
V10
Steps to reproduce:
1. Uninstall product config base
2. No products defined
3. Try to open product section

Current behavior:
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 827, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 849, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 4679, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 1518, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 4224, in _search
    query = self._where_calc(args)
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 4023, in _where_calc
    e = expression.expression(domain, self)
  File "/opt/odoo/odoo-10.0/odoo/osv/expression.py", line 643, in __init__
    self.parse()
  File "/opt/odoo/odoo-10.0/odoo/osv/expression.py", line 821, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field u'config_ok' in leaf "<osv.ExtendedLeaf: (u'config_ok', u'=', False) on product_template (ctx: )>"

Expected behavior:
Should be ble to uninstall
Video/Screenshot link (optional):

**Comment by PCatinean** [comment]
@sharkutz you're right, that's how it happens. If you upgrade product or base it should fix everything though granted the uninstall is not seamless.

**Comment by yostashiro** [comment]
> @sharkutz you're right, that's how it happens. If you upgrade product or base it should fix everything though granted the uninstall is not seamless.

You can alternatively remove the domain value `[('config_ok','=',False)]` from window actions `product.product_template_action` and `product.product_normal_action_sell`.
