### ISSUE TITLE
Traceback when creating order

### ISSUE THREAD

**Issue by CasVissers-360ERP** [pledra/odoo-product-configurator#98]
Impacted versions:
10.0

Steps to reproduce:
Create a template product

Current behavior:
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/bva/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/bva/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/bva/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/bva/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/bva/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/bva/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/odoo/bva/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/odoo/bva/odoo/addons/web/controllers/main.py", line 878, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/bva/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/bva/odoo/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/odoo/bva/odoo/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/bva/odoo/odoo/models.py", line 4686, in search_read
    result = records.read(fields)
  File "/odoo/odoo-product-configurator/product_configurator_wizard/wizard/product_configurator.py", line 568, in read
    custom_val = self.env.ref(custom_ext_id)
  File "/odoo/bva/odoo/odoo/api.py", line 785, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/odoo/bva/odoo/odoo/addons/base/ir/ir_model.py", line 1059, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
  File "/odoo/bva/odoo/odoo/addons/base/ir/ir_model.py", line 1043, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-11>", line 2, in xmlid_lookup
  File "/odoo/bva/odoo/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo/bva/odoo/odoo/addons/base/ir/ir_model.py", line 1032, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: product_configurator.custom_attribute_value

**Comment by CasVissers-360ERP** [comment]
Base update fixed it.
